import React, { useState, useEffect, useRef } from 'react';
import { Header } from './components/Header';
import { AuditInput } from './components/AuditInput';
import { LiveProgress } from './components/LiveProgress';
import { OverviewTab } from './components/OverviewTab';
import { IssuesTable } from './components/IssuesTable';
import { PageExplorer } from './components/PageExplorer';
import { PageDetailModal } from './components/PageDetailModal';
import { TechnicalTab } from './components/TechnicalTab';
import { OnPageTab } from './components/OnPageTab';
import { ContentTab } from './components/ContentTab';
import { LinksTab } from './components/LinksTab';
import { SitemapTab } from './components/SitemapTab';
import { RobotsTab } from './components/RobotsTab';
import { ReportModal } from './components/ReportModal';
import { HistoryList } from './components/HistoryList';
import {
  getRecentWebsites,
  addRecentWebsite,
  removeRecentWebsite,
  getUserAuditIds,
  addUserAuditId,
  removeUserAuditId,
} from './utils/recentWebsites';
import { safeFetchJson, getApiUrl } from './utils/apiClient';
import {
  Download,
  FileSpreadsheet,
  Printer,
  RotateCcw,
  LayoutDashboard,
  AlertCircle,
  FileText,
  SlidersHorizontal,
  Code2,
  Copy,
  Link2,
  Globe,
  ShieldCheck,
  ExternalLink,
} from 'lucide-react';
import type { AuditResult, AuditJob, CrawledPage, AuditHistoryItem, AuditErrorDetails } from './types';

export default function App() {
  const [activeJob, setActiveJob] = useState<AuditJob | null>(null);
  const [auditResult, setAuditResult] = useState<AuditResult | null>(null);
  const [activeTab, setActiveTab] = useState<string>('overview');
  const [selectedPage, setSelectedPage] = useState<CrawledPage | null>(null);
  const [showReportModal, setShowReportModal] = useState<boolean>(false);
  const [history, setHistory] = useState<AuditHistoryItem[]>([]);
  const [recentWebsites, setRecentWebsites] = useState<string[]>(() => getRecentWebsites());
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [errorDetails, setErrorDetails] = useState<AuditErrorDetails | null>(null);

  const eventSourceRef = useRef<EventSource | null>(null);
  const pollIntervalRef = useRef<number | null>(null);

  // Load past audits on mount
  useEffect(() => {
    loadHistory();
    return () => {
      cleanupStreams();
    };
  }, []);

  const cleanupStreams = () => {
    if (eventSourceRef.current) {
      eventSourceRef.current.close();
      eventSourceRef.current = null;
    }
    if (pollIntervalRef.current) {
      clearInterval(pollIntervalRef.current);
      pollIntervalRef.current = null;
    }
  };

  const loadHistory = async () => {
    try {
      const res = await safeFetchJson<AuditHistoryItem[]>('/api/audits');
      if (res.ok && Array.isArray(res.data)) {
        const data = res.data;
        const userIds = getUserAuditIds();
        const userUrls = getRecentWebsites().map(u => u.toLowerCase().replace(/\/+$/, ''));
        // Only display audit history specifically generated by this user in this browser
        const userAudits = data.filter(
          item => userIds.includes(item.id) || userUrls.includes(item.websiteUrl.toLowerCase().replace(/\/+$/, ''))
        );
        setHistory(userAudits);
      }
    } catch {
      // ignore
    }
  };

  const handleStartAudit = async (targetUrl: string, maxPages: number) => {
    setErrorMessage(null);
    setErrorDetails(null);
    setIsLoading(true);
    cleanupStreams();

    // Clear previous errors and initiate crawl
    try {
      const res = await safeFetchJson<{ jobId: string; url: string; maxPages: number }>('/api/audit/start', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: targetUrl, maxPages }),
      });

      if (!res.ok || !res.data) {
        const errorMsg = res.error || 'Failed to initiate crawl.';
        setErrorMessage(errorMsg);
        setErrorDetails(
          res.errorDetails || {
            type: 'crawl_error',
            errorType: 'Audit Failed',
            reason: 'START_FAILED',
            message: errorMsg,
            url: targetUrl,
          }
        );
        setIsLoading(false);
        const cleaned = removeRecentWebsite(targetUrl);
        setRecentWebsites(cleaned);
        return;
      }

      const data = res.data;

      // Initial job representation
      const initialJob: AuditJob = {
        id: data.jobId,
        url: data.url,
        maxPages: data.maxPages,
        status: 'crawling',
        progress: {
          step: 'validating',
          statusMessage: 'Starting crawler pipeline...',
          pagesDiscovered: 1,
          pagesCrawled: 0,
          currentUrl: data.url,
          percent: 0,
          recentLogs: [{ time: new Date().toLocaleTimeString(), message: 'Connecting to target host...', type: 'info' }],
        },
        createdAt: new Date().toISOString(),
      };

      setActiveJob(initialJob);
      setAuditResult(null);
      setIsLoading(false);

      // Start Server-Sent Events (SSE) listener
      try {
        const sseUrl = getApiUrl(`/api/audit/${data.jobId}/stream`);
        const es = new EventSource(sseUrl);
        eventSourceRef.current = es;

        es.onmessage = async (event) => {
          try {
            if (!event.data || typeof event.data !== 'string') return;
            const payload = JSON.parse(event.data);
            if (payload.status === 'crawling' && payload.progress) {
              setActiveJob(prev => prev ? { ...prev, progress: payload.progress } : null);
            } else if (payload.status === 'completed') {
              cleanupStreams();
              await loadCompletedAudit(payload.auditId);
            } else if (payload.status === 'failed') {
              cleanupStreams();
              setErrorMessage(payload.error || 'Crawl execution failed.');
              setErrorDetails(payload.errorDetails || null);
              setActiveJob(null);
              const cleaned = removeRecentWebsite(targetUrl);
              setRecentWebsites(cleaned);
            }
          } catch (e) {
            console.error('SSE event processing error:', e);
          }
        };

        es.onerror = () => {
          // SSE dropped, start fallback polling
          startPolling(data.jobId);
        };
      } catch {
        startPolling(data.jobId);
      }
    } catch (err: any) {
      const cleanMsg = err?.message || 'Network error communicating with audit server';
      setErrorMessage(cleanMsg);
      setErrorDetails({
        type: 'crawl_error',
        errorType: 'Network Error',
        reason: 'FETCH_FAILED',
        message: cleanMsg,
        url: targetUrl,
      });
      setIsLoading(false);
    }
  };

  const startPolling = (jobId: string) => {
    if (pollIntervalRef.current) return;

    pollIntervalRef.current = window.setInterval(async () => {
      try {
        const res = await safeFetchJson<any>(`/api/audit/${jobId}/status`);
        if (!res.ok || !res.data) return;
        const data = res.data;

        if (data.status === 'crawling' && data.progress) {
          setActiveJob(prev => prev ? { ...prev, progress: data.progress } : null);
        } else if (data.status === 'completed' && data.auditId) {
          cleanupStreams();
          await loadCompletedAudit(data.auditId);
        } else if (data.status === 'failed') {
          cleanupStreams();
          setErrorMessage(data.error || 'Crawl failed');
          setErrorDetails(data.errorDetails || null);
          setActiveJob(null);
          if (data.url) {
            const cleaned = removeRecentWebsite(data.url);
            setRecentWebsites(cleaned);
          }
        }
      } catch {
        // continue polling
      }
    }, 1000);
  };

  const loadCompletedAudit = async (auditId: string) => {
    try {
      const res = await safeFetchJson<AuditResult>(`/api/audit/${auditId}`);
      if (res.ok && res.data) {
        const audit = res.data;
        setAuditResult(audit);
        setActiveJob(null);
        setActiveTab('overview');
        // Register this audit ID to user's browser session
        addUserAuditId(auditId);
        // Also ensure website URL is in recent list
        const updated = addRecentWebsite(audit.websiteUrl);
        setRecentWebsites(updated);
        loadHistory();
      }
    } catch (e) {
      console.error('Failed to load audit result', e);
    }
  };

  const handleSelectAuditFromHistory = async (id: string) => {
    setErrorMessage(null);
    await loadCompletedAudit(id);
  };

  const handleDeleteAudit = async (id: string) => {
    try {
      await safeFetchJson(`/api/audits/${id}`, { method: 'DELETE' });
      removeUserAuditId(id);
      setHistory(prev => prev.filter(h => h.id !== id));
      if (auditResult && auditResult.id === id) {
        setAuditResult(null);
      }
    } catch {
      // ignore
    }
  };

  const handleSelectPageByUrl = (url: string) => {
    if (!auditResult) return;
    const found = auditResult.pages.find(p => p.url === url);
    if (found) {
      setSelectedPage(found);
    }
  };

  const handleExportCsv = () => {
    if (!auditResult) return;
    window.location.href = getApiUrl(`/api/audit/${auditResult.id}/export/csv`);
  };

  const handleExportJson = () => {
    if (!auditResult) return;
    window.location.href = getApiUrl(`/api/audit/${auditResult.id}/export/json`);
  };

  const TABS = [
    { id: 'overview', label: 'Overview', icon: LayoutDashboard },
    { id: 'issues', label: `Issues (${auditResult?.issueCounts.total || 0})`, icon: AlertCircle },
    { id: 'pages', label: `Pages (${auditResult?.pagesCrawledCount || 0})`, icon: FileText },
    { id: 'technical', label: 'Technical SEO', icon: SlidersHorizontal },
    { id: 'onpage', label: 'On-Page SEO', icon: Code2 },
    { id: 'content', label: 'Content', icon: Copy },
    { id: 'links', label: 'Links', icon: Link2 },
    { id: 'sitemap', label: 'Sitemap', icon: Globe },
    { id: 'robots', label: 'Robots.txt', icon: ShieldCheck },
  ];

  return (
    <div className="min-h-screen bg-[#FFF5ED]/50 flex flex-col font-['Inter'] text-[#000000]">
      {/* Persistent FWSC Header */}
      <Header
        isAuditing={!!activeJob && activeJob.status === 'crawling'}
        onNewAudit={() => {
          cleanupStreams();
          setActiveJob(null);
          setAuditResult(null);
          setErrorMessage(null);
          setErrorDetails(null);
        }}
      />

      {/* Secondary Top Information Bar */}
      <div className="bg-[#FFFDFB] border-b border-[#E5E5E5] py-2 px-4 sm:px-6 lg:px-8 shadow-[inset_0_-1px_0_rgba(0,0,0,0.02)]">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2 text-xs">
          <div className="flex items-center gap-2">
            <span className="font-bold text-[#000000] tracking-wide">FWSC</span>
            <span className="text-[#BBBBBB]">•</span>
            <span className="text-[#555555]">
              Free Website SEO Checker <span className="text-[#888888]">by</span>{' '}
              <span className="font-semibold text-[#000000]">digiVirus</span>
            </span>
          </div>
          <div className="flex items-center gap-2 text-[#555555]">
            <span className="inline-block w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            <span className="font-medium">100% API-free website crawling and SEO analysis</span>
          </div>
        </div>
      </div>

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6">
        {/* VIEW 1: LIVE CRAWL PROGRESS */}
        {activeJob && activeJob.status === 'crawling' ? (
          <LiveProgress
            progress={activeJob.progress}
            targetUrl={activeJob.url}
            maxPages={activeJob.maxPages}
            onCancel={() => {
              cleanupStreams();
              setActiveJob(null);
            }}
          />
        ) : auditResult ? (
          /* VIEW 2: AUDIT RESULTS DASHBOARD */
          <div className="space-y-6">
            {/* Top Dashboard Header */}
            <div className="bg-white rounded-2xl border border-[#E5E5E5] p-6 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-[#F29627]">
                    Audit Completed
                  </span>
                  <span className="text-[#888888] text-xs">•</span>
                  <span className="text-xs text-[#666666]">
                    {new Date(auditResult.createdAt).toLocaleDateString()} at{' '}
                    {new Date(auditResult.createdAt).toLocaleTimeString()}
                  </span>
                </div>
                <h1 className="font-['Poppins'] text-2xl sm:text-3xl font-extrabold text-[#000000] mt-1 flex items-center gap-2">
                  <span>{auditResult.normalizedDomain}</span>
                  <a
                    href={auditResult.websiteUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="text-[#888888] hover:text-[#F29627] transition-colors"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                </h1>
                <p className="text-xs text-[#555555] font-mono mt-0.5">
                  Target URL: {auditResult.websiteUrl} ({auditResult.pagesCrawledCount} pages audited)
                </p>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap items-center gap-2">
                <button
                  id="export-csv-button"
                  onClick={handleExportCsv}
                  className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white border border-[#E5E5E5] text-xs font-bold text-[#333333] hover:border-[#F29627] hover:text-[#F29627] transition-colors cursor-pointer shadow-xs"
                >
                  <FileSpreadsheet className="w-4 h-4 text-[#F29627]" />
                  <span>Export CSV</span>
                </button>

                <button
                  id="export-json-button"
                  onClick={handleExportJson}
                  className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white border border-[#E5E5E5] text-xs font-bold text-[#333333] hover:border-[#F29627] hover:text-[#F29627] transition-colors cursor-pointer shadow-xs"
                >
                  <Download className="w-4 h-4 text-[#F29627]" />
                  <span>Export JSON</span>
                </button>

                <button
                  id="view-report-button"
                  onClick={() => setShowReportModal(true)}
                  className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-[#000000] text-white text-xs font-bold hover:bg-[#222222] transition-colors cursor-pointer shadow-xs"
                >
                  <Printer className="w-4 h-4 text-[#F29627]" />
                  <span>Print Report</span>
                </button>

                <button
                  id="audit-another-btn"
                  onClick={() => {
                    cleanupStreams();
                    setActiveJob(null);
                    setAuditResult(null);
                    setErrorMessage(null);
                    setErrorDetails(null);
                  }}
                  className="inline-flex items-center gap-1 px-3 py-2 rounded-xl bg-[#FFF5ED] border border-[#F29627]/30 text-xs font-bold text-[#F29627] hover:bg-[#F29627] hover:text-white transition-all cursor-pointer"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  <span>New Site</span>
                </button>
              </div>
            </div>

            {/* Navigation Tabs Bar */}
            <div className="bg-white rounded-2xl border border-[#E5E5E5] p-1.5 shadow-xs overflow-x-auto flex gap-1">
              {TABS.map((tab) => {
                const Icon = tab.icon;
                const isActive = activeTab === tab.id;
                return (
                  <button
                    key={tab.id}
                    id={`tab-${tab.id}`}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center gap-2 px-3.5 py-2.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
                      isActive
                        ? 'bg-[#F29627] text-white shadow-[0_2px_8px_rgba(242,150,39,0.3)]'
                        : 'text-[#555555] hover:text-[#000000] hover:bg-[#F5F5F5]'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    <span>{tab.label}</span>
                  </button>
                );
              })}
            </div>

            {/* TAB CONTENTS */}
            {activeTab === 'overview' && (
              <OverviewTab
                audit={auditResult}
                onNavigateTab={(tab) => setActiveTab(tab)}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'issues' && (
              <IssuesTable
                issues={auditResult.issues}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'pages' && (
              <PageExplorer
                pages={auditResult.pages}
                onSelectPage={(page) => setSelectedPage(page)}
              />
            )}

            {activeTab === 'technical' && (
              <TechnicalTab
                pages={auditResult.pages}
                issues={auditResult.issues}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'onpage' && (
              <OnPageTab
                pages={auditResult.pages}
                issues={auditResult.issues}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'content' && (
              <ContentTab
                pages={auditResult.pages}
                duplicates={auditResult.duplicatePairs}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'links' && (
              <LinksTab
                pages={auditResult.pages}
                brokenLinks={auditResult.brokenLinks}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'sitemap' && (
              <SitemapTab
                sitemap={auditResult.sitemapAnalysis}
                onSelectPage={handleSelectPageByUrl}
              />
            )}

            {activeTab === 'robots' && (
              <RobotsTab robots={auditResult.robotsAnalysis} />
            )}
          </div>
        ) : (
          /* VIEW 3: INITIAL LAUNCH SCREEN */
          <div>
            <AuditInput
              onStartAudit={handleStartAudit}
              isLoading={isLoading}
              error={errorMessage}
              errorDetails={errorDetails}
              recentWebsites={recentWebsites}
            />

            {/* Recent Audits History */}
            <HistoryList
              history={history}
              onSelectAudit={handleSelectAuditFromHistory}
              onDeleteAudit={handleDeleteAudit}
            />
          </div>
        )}

        {/* PAGE DRILL-DOWN MODAL */}
        {selectedPage && auditResult && (
          <PageDetailModal
            page={selectedPage}
            allIssues={auditResult.issues}
            onClose={() => setSelectedPage(null)}
            onNavigatePage={handleSelectPageByUrl}
          />
        )}

        {/* PRINTABLE REPORT MODAL */}
        {showReportModal && auditResult && (
          <ReportModal
            audit={auditResult}
            onClose={() => setShowReportModal(false)}
          />
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-[#E5E5E5] bg-white py-8 mt-16 text-center text-xs text-[#777777]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex flex-col sm:flex-row items-center gap-4">
            <a
              href="https://digivirus.in"
              target="_blank"
              rel="noreferrer"
              className="inline-block hover:opacity-85 transition-opacity"
            >
              <img
                src="/digivirus-logo.png"
                alt="digiVirus"
                className="h-7 w-auto object-contain"
                referrerPolicy="no-referrer"
              />
            </a>
            <div className="h-4 w-px bg-[#E5E5E5] hidden sm:block"></div>
            <div className="text-center sm:text-left">
              <p className="font-['Poppins'] font-bold text-sm text-[#000000]">
                FWSC <span className="font-normal text-xs text-[#666666]">— Free Website SEO Checker</span>
              </p>
              <p className="text-[11px] text-[#888888] mt-0.5">
                Brand attribution: <span className="font-semibold text-[#000000]">by digiVirus</span>
              </p>
            </div>
          </div>
          <div className="text-center md:text-right space-y-1">
            <p className="font-medium text-[#333333]">
              100% API-free website crawling and SEO analysis
            </p>
            <p className="text-[11px] text-[#888888]">
              Direct crawler analysis engine • Zero external SEO APIs
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
